# H2 DB Config
# spring.datasource.url=jdbc:h2:mem:testdb

# # For the save the data within a file
spring.datasource.url=jdbc:h2:file:./data/testdb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=shantanu
spring.datasource.password=shantanu
spring.jpa.hibernate.ddl-auto=update
server.port=9090

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Allow console from browser
spring.h2.console.settings.web-allow-others=true